baseURL = 'https://qilong75.github.io/'
languageCode = 'zh-cn'
title = 'Happy Cloud'
theme = 'maverick'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[permalinks]
  pages = "/:slug"

[params]
  # description = "A technology blog about software testing and test automation tips and tutorials by Marie Cruz."
  author = 'Jia Qi Long'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
  # [[menu.main]]
  #   identifier = "courses"
  #   name = "Courses"
  #   url = "/courses/"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  # [[menu.main]]
  #   identifier = "speaking"
  #   name = "Speaking"
  #   url = "/speaking/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
